COLUMNS:
  status: object
  duration: int64
  credit_history: object
  purpose: object
  amount: int64
  savings: object
  employment_duration: object
  installment_rate: object
  personal_status_sex: object
  other_debtors: object
  present_residence: object
  property: object
  age: int64
  other_installment_plans: object
  housing: object
  number_credits: object
  job: object
  people_liable: object
  telephone: object
  foreign_worker: object
  credit_risk: object



TARGET_COLUMN:
  name: credit_risk
